# Manifest for this project. See https://luaupm.com/docs
# Add dependencies with `lpm add <scope/name>`, then run `lpm install`.

[dependencies]
Promise = { name = "howmanysmall/typed-promise", version = "^", index = "wally" }
ProfileStore = { name = "lm-loleris/profilestore", version = "^", index = "wally" }
Charm = { name = "littensy/charm", version = "^", index = "wally" }
CharmSync = { name = "littensy/charm-sync", version = "^", index = "wally" }
Vide = { name = "centau/vide", version = "^", index = "wally" }
VideCharm = { name = "littensy/vide-charm", version = "^", index = "wally" }
UiLabs = { name = "pepeeltoro41/ui-labs", version = "^", index = "wally" }
Conch = { name = "alicesaidhi/conch", version = "0.4.0-rc.9", index = "wally" }
ConchUi = { name = "alicesaidhi/conch-ui", version = "0.4.0-rc.9", index = "wally" }
Iris = { name = "sirmallard/iris", version = "^", index = "wally" }
TypeForge = { name = "cameronpcampbell/typeforge", version = "^", index = "wally" }
Signal = { name = "molyidev/signal", version = "^", index = "pesde" }
Scythe = { name = "synttx/scythe", version = "^", index = "wally", entry = "scythe" }
Vow = { name = "synttx/vow", version = "^", index = "wally", entry = "vow" }

[indices]
wally = "https://github.com/UpliftGames/wally-index"
pesde = "https://github.com/pesde-pkg/index"

[overrides]
"CharmSync.Charm" = "Charm"
"ConchUi.vide" = "Vide"

[tools]
blink = "1axen/blink@0.18.8"
argon = "argon-rbx/argon@2.0.29"
stylua = "johnnymorganz/stylua@2.5.2"
selene = "kampfkarren/selene@0.31.0"
luau-lsp = "johnnymorganz/luau-lsp@1.69.0"

[patches]
"centau/vide@0.4.1" = "patches/centau_vide@0.4.1.patch"
