name = "studio713/roblox_game_template"
version = "0.1.0"
description = "A game template"
authors = ["vermale713"]
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_argon", version = "^0.2.0", target = "lune" }
argon = { name = "pesde/argon", version = "^2.0.28", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
Promise = { wally = "howmanysmall/typed-promise", version = "^4.0.6" }
ProfileStore = { wally = "lm-loleris/profilestore", version = "^1.0.3" }
Charm = { wally = "littensy/charm", version = "^0.11.0-rc.6" }
CharmSync = { wally = "littensy/charm-sync", version = "^0.4.0-rc.7" }
UiLabs = { wally = "pepeeltoro41/ui-labs", version = "^2.4.2" }
Fluid = { wally = "ffrostfall/fluid", version = "^0.6.4" }
Conch = { wally = "alicesaidhi/conch", version = "^0.4.0-rc.9" }
ConchUi = { wally = "alicesaidhi/conch-ui", version = "^0.4.0-rc.9" }
Signal = { name = "molyidev/signal", version = "^1.0.3" }
Iris = { wally = "sirmallard/iris", version = "^2.5.1" }